
    create table Asociacion (
        id bigint generated by default as identity (start with 1),
        latitud double,
        longitud double,
        primary key (id)
    )

    create table Asociacion_PublicacionInteresadoEnAdopcion (
        Asociacion_id bigint not null,
        publicacionInteresadoEnAdopcion_id bigint not null
    )

    create table Asociacion_PublicacionMascotaEnAdopcion (
        Asociacion_id bigint not null,
        publicacionesDeMascotasEnAdopcion_id bigint not null
    )

    create table Asociacion_PublicacionMascotaPerdida (
        Asociacion_id bigint not null,
        publicacionesDeMascotasPerdidas_id bigint not null
    )

    create table Duenio (
        id bigint generated by default as identity (start with 1),
        persona_id bigint,
        primary key (id)
    )

    create table Mascota (
        id bigint generated by default as identity (start with 1),
        apodo varchar(255),
        descripcion varchar(255),
        edad smallint,
        especie integer,
        nombre varchar(255),
        sexo integer,
        tamanio integer,
        primary key (id)
    )

    create table MascotaPerdida (
        id bigint generated by default as identity (start with 1),
        descripcionEstado varchar(255),
        latitud double,
        longitud double,
        primary key (id)
    )

    create table Persona (
        id bigint generated by default as identity (start with 1),
        fechaNacimiento varbinary(255),
        nombreYApellido varchar(255),
        primary key (id)
    )

    create table PosiblesCaracteristicas (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table PosiblesCaracteristicas_caracteristicas (
        PosiblesCaracteristicas_id bigint not null,
        valor varchar(255),
        nombre_caracteristica varchar(255) not null,
        primary key (PosiblesCaracteristicas_id, nombre_caracteristica)
    )

    create table PublicacionInteresadoEnAdopcion (
        id bigint generated by default as identity (start with 1),
        persona_id bigint,
        primary key (id)
    )

    create table PublicacionMascotaEnAdopcion (
        id bigint generated by default as identity (start with 1),
        mascota_id bigint,
        primary key (id)
    )

    create table PublicacionMascotaPerdida (
        id bigint generated by default as identity (start with 1),
        aprobado boolean,
        rescatista_id bigint,
        primary key (id)
    )

    create table Rescatista (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        primary key (id)
    )

    create table caracteristicas_mapping (
        mascota_id bigint not null,
        valor varchar(255),
        nombre_caracteristica varchar(255) not null,
        primary key (mascota_id, nombre_caracteristica)
    )

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint UK_hg6pldtmjnuclnqbfgq4tcj79  unique (publicacionInteresadoEnAdopcion_id)

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint UK_93ta7rnbj8vk5bigflydjsdy0  unique (publicacionesDeMascotasEnAdopcion_id)

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint UK_ehu8fj87j1cvyeuoxxecr0qwx  unique (publicacionesDeMascotasPerdidas_id)

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint FK_hg6pldtmjnuclnqbfgq4tcj79 
        foreign key (publicacionInteresadoEnAdopcion_id) 
        references PublicacionInteresadoEnAdopcion

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint FK_gs2dspx9hjfjra67tq3vc25gr 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint FK_93ta7rnbj8vk5bigflydjsdy0 
        foreign key (publicacionesDeMascotasEnAdopcion_id) 
        references PublicacionMascotaEnAdopcion

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint FK_lqlssref0xmjv44s523qv0431 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint FK_ehu8fj87j1cvyeuoxxecr0qwx 
        foreign key (publicacionesDeMascotasPerdidas_id) 
        references PublicacionMascotaPerdida

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint FK_6mr14wfsvnnmtc6sq9vm6687h 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Duenio 
        add constraint FK_ljqg8vj3y1uscel2sdbl6t8ps 
        foreign key (persona_id) 
        references Persona

    alter table PosiblesCaracteristicas_caracteristicas 
        add constraint FK_rvs7bl7wyirw0xahy9pt4vpn0 
        foreign key (PosiblesCaracteristicas_id) 
        references PosiblesCaracteristicas

    alter table PublicacionInteresadoEnAdopcion 
        add constraint FK_aemp1m4f6gmptlkapmxakfot 
        foreign key (persona_id) 
        references Persona

    alter table PublicacionMascotaEnAdopcion 
        add constraint FK_35uijj9sam9y736yed0u0mcd8 
        foreign key (mascota_id) 
        references Mascota

    alter table PublicacionMascotaPerdida 
        add constraint FK_idcp4b6p9hxo3gg1qy9m57rwq 
        foreign key (rescatista_id) 
        references Rescatista

    alter table caracteristicas_mapping 
        add constraint FK_tpjprt1to2n1thsr1e741bu80 
        foreign key (mascota_id) 
        references Mascota
