
    create table Asociacion (
        id bigint generated by default as identity (start with 1),
        latitud double,
        longitud double,
        primary key (id)
    )

    create table Asociacion_PublicacionInteresadoEnAdopcion (
        Asociacion_id bigint not null,
        publicacionInteresadoEnAdopcion_id bigint not null
    )

    create table Asociacion_PublicacionMascotaEnAdopcion (
        Asociacion_id bigint not null,
        publicacionesDeMascotasEnAdopcion_id bigint not null
    )

    create table Asociacion_PublicacionMascotaPerdida (
        Asociacion_id bigint not null,
        publicacionesDeMascotasPerdidas_id bigint not null
    )

    create table Duenio (
        id bigint generated by default as identity (start with 1),
        persona_id bigint,
        primary key (id)
    )

    create table Duenio_Mascota (
        Duenio_id bigint not null,
        mascotas_id bigint not null
    )

    create table Mailer (
        id bigint generated by default as identity (start with 1),
        clave varchar(255),
        remitente varchar(255),
        primary key (id)
    )

    create table Mascota (
        id bigint generated by default as identity (start with 1),
        apodo varchar(255),
        descripcion varchar(255),
        edad smallint,
        especie integer,
        nombre varchar(255),
        sexo integer,
        tamanio integer,
        primary key (id)
    )

    create table MascotaPerdida (
        id bigint generated by default as identity (start with 1),
        descripcionEstado varchar(255),
        latitud double,
        longitud double,
        primary key (id)
    )

    create table MedioNotificacion (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        mailer_id bigint,
        smser_id bigint,
        primary key (id)
    )

    create table Perfil (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        clave varchar(255),
        usuario varchar(255),
        duenio_id bigint,
        asociacion_id bigint,
        primary key (id)
    )

    create table Persona (
        id bigint generated by default as identity (start with 1),
        fechaNacimiento varbinary(255),
        nombreYApellido varchar(255),
        primary key (id)
    )

    create table PosiblesCaracteristicas (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Pregunta (
        id bigint generated by default as identity (start with 1),
        cuerpoDuenio varchar(255),
        cuerpoInteresado varchar(255),
        visible boolean not null,
        primary key (id)
    )

    create table Pregunta_opciones (
        Pregunta_id bigint not null,
        opciones varchar(255)
    )

    create table PublicacionInteresadoEnAdopcion (
        id bigint generated by default as identity (start with 1),
        persona_id bigint,
        primary key (id)
    )

    create table PublicacionInteresadoEnAdopcion_Respuesta (
        PublicacionInteresadoEnAdopcion_id bigint not null,
        respuestas_id bigint not null
    )

    create table PublicacionMascotaEnAdopcion (
        id bigint generated by default as identity (start with 1),
        mascota_id bigint,
        primary key (id)
    )

    create table PublicacionMascotaEnAdopcion_Respuesta (
        PublicacionMascotaEnAdopcion_id bigint not null,
        respuestas_id bigint not null
    )

    create table PublicacionMascotaPerdida (
        id bigint generated by default as identity (start with 1),
        aprobado boolean,
        rescatista_id bigint,
        primary key (id)
    )

    create table Rescatista (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        mascota_id bigint,
        persona_id bigint,
        primary key (id)
    )

    create table Respuesta (
        id bigint generated by default as identity (start with 1),
        respuesta varchar(255),
        pregunta_id bigint,
        primary key (id)
    )

    create table Smser (
        id bigint generated by default as identity (start with 1),
        accountSid varchar(255),
        authToken varchar(255),
        senderNumber varchar(255),
        primary key (id)
    )

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint UK_hg6pldtmjnuclnqbfgq4tcj79  unique (publicacionInteresadoEnAdopcion_id)

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint UK_93ta7rnbj8vk5bigflydjsdy0  unique (publicacionesDeMascotasEnAdopcion_id)

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint UK_ehu8fj87j1cvyeuoxxecr0qwx  unique (publicacionesDeMascotasPerdidas_id)

    alter table Duenio_Mascota 
        add constraint UK_qpipeipxqev8ej5l4ncemhtiu  unique (mascotas_id)

    alter table PublicacionInteresadoEnAdopcion_Respuesta 
        add constraint UK_fx6g0ir1jr4g3vapf9h5h9ba4  unique (respuestas_id)

    alter table PublicacionMascotaEnAdopcion_Respuesta 
        add constraint UK_gydw5ylm6yg6txtkogo5gbjm  unique (respuestas_id)

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint FK_hg6pldtmjnuclnqbfgq4tcj79 
        foreign key (publicacionInteresadoEnAdopcion_id) 
        references PublicacionInteresadoEnAdopcion

    alter table Asociacion_PublicacionInteresadoEnAdopcion 
        add constraint FK_gs2dspx9hjfjra67tq3vc25gr 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint FK_93ta7rnbj8vk5bigflydjsdy0 
        foreign key (publicacionesDeMascotasEnAdopcion_id) 
        references PublicacionMascotaEnAdopcion

    alter table Asociacion_PublicacionMascotaEnAdopcion 
        add constraint FK_lqlssref0xmjv44s523qv0431 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint FK_ehu8fj87j1cvyeuoxxecr0qwx 
        foreign key (publicacionesDeMascotasPerdidas_id) 
        references PublicacionMascotaPerdida

    alter table Asociacion_PublicacionMascotaPerdida 
        add constraint FK_6mr14wfsvnnmtc6sq9vm6687h 
        foreign key (Asociacion_id) 
        references Asociacion

    alter table Duenio 
        add constraint FK_ljqg8vj3y1uscel2sdbl6t8ps 
        foreign key (persona_id) 
        references Persona

    alter table Duenio_Mascota 
        add constraint FK_qpipeipxqev8ej5l4ncemhtiu 
        foreign key (mascotas_id) 
        references Mascota

    alter table Duenio_Mascota 
        add constraint FK_hynmo2ivhse330d9xq596389b 
        foreign key (Duenio_id) 
        references Duenio

    alter table MedioNotificacion 
        add constraint FK_gyjjd9fsp9t7pqdbu2ql06plm 
        foreign key (mailer_id) 
        references Mailer

    alter table MedioNotificacion 
        add constraint FK_tmwciadcp2fgcs7eghji5wgth 
        foreign key (smser_id) 
        references Smser

    alter table Perfil 
        add constraint FK_5hpdkt7a38omibdc3uu4ing6s 
        foreign key (duenio_id) 
        references Duenio

    alter table Perfil 
        add constraint FK_jai3ho8jnwyphjp80v1x0o1of 
        foreign key (asociacion_id) 
        references Asociacion

    alter table Pregunta_opciones 
        add constraint FK_mw94rc1yg3ip98pc65sp2iq3e 
        foreign key (Pregunta_id) 
        references Pregunta

    alter table PublicacionInteresadoEnAdopcion 
        add constraint FK_aemp1m4f6gmptlkapmxakfot 
        foreign key (persona_id) 
        references Persona

    alter table PublicacionInteresadoEnAdopcion_Respuesta 
        add constraint FK_fx6g0ir1jr4g3vapf9h5h9ba4 
        foreign key (respuestas_id) 
        references Respuesta

    alter table PublicacionInteresadoEnAdopcion_Respuesta 
        add constraint FK_2cra12knmj8botih68u89q2vc 
        foreign key (PublicacionInteresadoEnAdopcion_id) 
        references PublicacionInteresadoEnAdopcion

    alter table PublicacionMascotaEnAdopcion 
        add constraint FK_35uijj9sam9y736yed0u0mcd8 
        foreign key (mascota_id) 
        references Mascota

    alter table PublicacionMascotaEnAdopcion_Respuesta 
        add constraint FK_gydw5ylm6yg6txtkogo5gbjm 
        foreign key (respuestas_id) 
        references Respuesta

    alter table PublicacionMascotaEnAdopcion_Respuesta 
        add constraint FK_nlftof07npfq4ydv1467b3ku4 
        foreign key (PublicacionMascotaEnAdopcion_id) 
        references PublicacionMascotaEnAdopcion

    alter table PublicacionMascotaPerdida 
        add constraint FK_idcp4b6p9hxo3gg1qy9m57rwq 
        foreign key (rescatista_id) 
        references Rescatista

    alter table Rescatista 
        add constraint FK_au1kf4s3opx6jpvru34m1b8fx 
        foreign key (mascota_id) 
        references MascotaPerdida

    alter table Rescatista 
        add constraint FK_4glsf37c37rs0wotp5xbj807m 
        foreign key (persona_id) 
        references Persona

    alter table Respuesta 
        add constraint FK_6u4tlwh295l76h26254mmulpi 
        foreign key (pregunta_id) 
        references Pregunta
